title: Nathan Josue's Portfolio
description: Robotics, Web Development, and AI Usage
author: Nathan Josue
email: nathanjosue1017@gmail.com
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
url: "https://github.com/PresJosue"
